# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161211_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
