# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161211_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
