# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
