# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161220_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='imageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
