# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20161220_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='imageid',
            new_name='post_imageid',
        ),
    ]
