# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20161220_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post_imageid',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
