# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_imageupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='imageupload',
            name='created',
            field=models.DateTimeField(default=None),
        ),
    ]
